<?php

// database/migrations/xxxx_xx_xx_create_orders_table.php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('orders', function (Blueprint $table) {
            $table->id(); // Standard internal auto-increment ID
            $table->uuid('uuid')->unique(); // Generated by React Native tablet for offline sync mapping
            $table->foreignId('store_id')->constrained()->onDelete('cascade');
            $table->foreignId('user_id')->nullable()->constrained(); // Cashier who took the order

            // France Compliance: Sequence number per store (cannot have gaps)
            $table->unsignedBigInteger('sequence_number'); 
            
            // Financial details (storing decimals accurately)
            $table->decimal('subtotal_excl_vat', 10, 2); // HT
            $table->decimal('vat_amount', 10, 2);        // TVA total
            $table->decimal('total_incl_vat', 10, 2);   // TTC

            // France Compliance: Cryptographic chaining
            // Every transaction must hash its own data + the hash of the transaction before it.
            $table->string('hash', 64)->nullable(); 
            $table->string('previous_hash', 64)->nullable();

            $table->string('status')->default('completed'); // e.g., completed, cancelled
            $table->timestamp('completed_at'); // Original timestamp when customer paid (even if offline)
            $table->timestamps(); // Created_at (when server received it) and Updated_at
            
            // Unique index to prevent duplicate sequence numbers within the same store
            $table->unique(['store_id', 'sequence_number']);
        });
    }

    public function down(): void {
        Schema::dropIfExists('orders');
    }
};
